name: Validar proyecto
on: 
    push:

    pull_request:

jobs:

      validar:


      runs-on: ubuntu-lastest

      steps:
        - name: Descargar Proyecto
          uses: actions/checkout@v4

          name: Configuracion Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Validar sintaxis Python
          run: python -m py_compile precios.py
